version: "3.9"
services:
  Percona:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /home/idenis/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 3151020
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: 123qwe
      MYSQL_DATABASE: wpdb

  NGINX:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - /home/idenis/nginx:/usr/share/nginx/html
